// <auto-generated />
namespace EmptyASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingmodelTabel7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingmodelTabel7));
        
        string IMigrationMetadata.Id
        {
            get { return "201904151408192_addingmodelTabel7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
